app:
  version: 'permitted-places-FX'

http:
  port: '8082'

logger:
  log_level: 'debug'
  rollbar_env: 'permitted-places-FX'
dbconfig:
  portdb: '5432'
  user: 'Yuta'
  password: '123456'
  adress: '127.0.0.1'